name: GitHub 3D Profile
on:
  schedule: [{ cron: "0 18 * * *" }]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: aliammari1
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: main
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
